In [223]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.sentiment.vader import SentimentIntensityAnalyzer

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('vader_lexicon')
import os
import numpy as np
import re
from dotenv import load_dotenv
load_dotenv()
sentiment_analyzer = SentimentIntensityAnalyzer()

[nltk_data] Downloading package stopwords to /Users/alexandernarvaez-
[nltk_data]     duckworth/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/alexandernarvaez-
[nltk_data]     duckworth/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/alexandernarvaez-duckworth/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [224]:
maxTweets = 10000

tweets_list1 = []

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:elonmusk').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [225]:
# tweets_list2 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:michael_saylor').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [226]:
# tweets_list3 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:CoinDesk').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list3.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [227]:
# tweets_list4 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:woonomic').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list4.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [228]:
# tweets_list5 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:AltcoinDailyio').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list5.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [229]:
# tweets_list6 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:TheCryptoLark').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list6.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [230]:
# tweets_list7 = []

# for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:360_trader').get_items()):
#     if i>maxTweets:
#         break
#     tweets_list7.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

In [231]:
elon = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# mike = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# CoinDesk = pd.DataFrame(tweets_list3, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# woo = pd.DataFrame(tweets_list4, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# altcoin = pd.DataFrame(tweets_list5, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# lark = pd.DataFrame(tweets_list6, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")
# t360 = pd.DataFrame(tweets_list7, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])#,parse_dates=True, index_col="Datetime")

In [232]:
elon.tail()

elon['Datetime'] = pd.to_datetime(elon['Datetime'], format='%Y-%m-%d')
elon['Datetime'] = elon['Datetime']
elon.set_index('Datetime',inplace=True)
elon

,Tweet Id,Text,Username
Datetime,,,
2021-05-27 21:32:40+00:00,1398029410289127424,@Model3Owners Tesla sure would appreciate chan...,elonmusk
2021-05-27 16:29:47+00:00,1397953188163096582,@waitbutwhy @poweredbyart Exactly,elonmusk
2021-05-27 06:49:30+00:00,1397807157094014979,"@RationalEtienne @SciGuySpace Potentially, 100...",elonmusk
2021-05-27 01:17:39+00:00,1397723641144504321,@AlexSvanArt @Neopork85 Pretty close. No tiles...,elonmusk
2021-05-27 00:41:24+00:00,1397714521066639362,@SciGuySpace Cumulative payload to orbit is th...,elonmusk
...,...,...,...
2017-08-14 23:05:33+00:00,897232757629173760,Tesla Powerwalls can support houses of any siz...,elonmusk
2017-08-14 22:26:47+00:00,897223001631899648,@neddesmond @SpaceX The danger is def high for...,elonmusk
2017-08-14 22:19:16+00:00,897221108704751616,"@neddesmond @SpaceX We certainly could, but, w...",elonmusk
2017-08-14 17:05:34+00:00,897142164731199488,12th mission of our Dragon robotic space freig...,elonmusk
2017-08-13 15:56:46+00:00,896762461574938625,First draft animation of the Falcon Heavy thre...,elonmusk

In [233]:
elon = elon.loc[:'2021-04-30']

In [234]:
elon[['Text']].dtypes

Text    object
dtype: object

In [238]:
#for i in elon[['Text']]:


#     sentiment = analyzer.polarity_scores(text)
#         compound = sentiment["compound"]
#         pos = sentiment["pos"]
#         neu = sentiment["neu"]
#         neg = sentiment["neg"]
        
          
sentiments = []

for i in range(len(elon)):
    try:
        text = elon["Text"][i]
        sentiment = sentiment_analyzer.polarity_scores(text)
        compound = sentiment["compound"]
        pos = sentiment["pos"]
        neu = sentiment["neu"]
        neg = sentiment["neg"]
        
        sentiments.append({
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu
            
        })
        
    except AttributeError:
        pass
    
    
elon_sent_df = pd.DataFrame(sentiments)

In [239]:
elon_sent_df

     compound  positive  negative  neutral
0      0.6476     0.306     0.000    0.694
1      0.0000     0.000     0.000    1.000
2      0.0000     0.000     0.000    1.000
3      0.2500     0.113     0.077    0.810
4     -0.2766     0.060     0.103    0.837
..        ...       ...       ...      ...
160    0.0000     0.000     0.000    1.000
161   -0.7964     0.000     0.645    0.355
162    0.4019     0.730     0.000    0.270
163    0.0000     0.000     0.000    1.000
164    0.0000     0.000     0.000    1.000

[165 rows x 4 columns]

In [240]:
elon

,Tweet Id,Text,Username
Datetime,,,
2021-05-27 21:32:40+00:00,1398029410289127424,@Model3Owners Tesla sure would appreciate chan...,elonmusk
2021-05-27 16:29:47+00:00,1397953188163096582,@waitbutwhy @poweredbyart Exactly,elonmusk
2021-05-27 06:49:30+00:00,1397807157094014979,"@RationalEtienne @SciGuySpace Potentially, 100...",elonmusk
2021-05-27 01:17:39+00:00,1397723641144504321,@AlexSvanArt @Neopork85 Pretty close. No tiles...,elonmusk
2021-05-27 00:41:24+00:00,1397714521066639362,@SciGuySpace Cumulative payload to orbit is th...,elonmusk
...,...,...,...
2021-05-01 21:56:54+00:00,1388613426868625416,Baby Shark &amp; Shark Tank merge to form Baby...,elonmusk
2021-05-01 21:53:38+00:00,1388612603480510469,Irony Man â€“ defeats villains using the power o...,elonmusk
2021-05-01 21:51:22+00:00,1388612033160126469,@gshenanigans1 Definitely,elonmusk
2021-05-01 21:49:50+00:00,1388611645560262660,Throwing out some skit ideas for SNL. What sho...,elonmusk
2021-05-01 21:36:22+00:00,1388608259255377920,Woke James Bond\nSNL May 8,elonmusk

In [ ]:
pd.concat()